name: glutton
description: Flutter shared preferences customized plugin. Secure, Encrypted, Simplified use, Simple key-value pairs storage.
version: 1.0.5
homepage: https://github.com/agungnursatria/glutton

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.3
  encrypt: ^5.0.0-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
